Check if branch exists before checkout*
Solves git's warning[0] about untracked files when trying `git checkout
work-end-checkpoint`. We get the error when the local
'work-end-checkpoint' branch doesn't exist (deleted by 1st call to `work
start`) but the remote one does. Deleting the remote branch will also
work: `git push private :work-end-checkpoint`

[0]:
error: The following untracked working tree files would be overwritten by checkout:
    (...untracked files...)
Please move or remove them before you can switch branches.
Aborting